# Generated by Django 4.1.7 on 2023-03-25 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'Electrical'), (2, 'Carpentry'), (3, 'Plumbing')])),
                ('resolved', models.BooleanField(default=False)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.room')),
            ],
            options={
                'unique_together': {('issue', 'room')},
            },
        ),
    ]
