# Generated by Django 4.1.7 on 2023-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_reported_alter_category_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='amount_issues',
            field=models.IntegerField(default=0),
        ),
    ]
